on:
  workflow_call:
    inputs:
      
      artifact:
        required: true
        type: string

      dependency:
        type: string
      
      repository:
        required: true
        type: string
      
      tags:
        required: true
        type: string
  
jobs:
 build-image:
   runs-on: ubuntu-latest
   needs: ${{inputs.dependency}}
   steps:
     - name: Login Fake 
       run: |
           echo "paramter value passed from above"
           echo ${{ inputs.name }}
           echo "SECRET" 
