on:
  workflow_call:
    inputs:

      artifact:
        required: true
        type: string

      repository:
        required: true
        type: string
      
      tags:
        required: true
        type: string
  
jobs:
 build-image:
   runs-on: ubuntu-latest
   #needs: build-image
   steps:
     - name: Login Fake 
       run: |
           echo "paramter value passed from above"
           echo ${{ inputs.name }}
           echo "SECRET" 
