on:
  workflow_call:
    inputs:

      artifact:
        required: true
        type: string

      repository:
        required: true
        type: string
      
      tags:
        required: true
        type: string
  
jobs:
 build-docker-image:
   runs-on: ubuntu-latest
   steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}