on:
  workflow_call:
    inputs:
      projectPath:
        required: true
        type: string
        default: '**.csproj'

      dotnet-version:
        type: string
        default: "6.0.x"

jobs:

 dotnet-build-code:
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v3
     
     - name: Setup .NET Core SDK ${{ inputs.dotnet-version }}
       uses: actions/setup-dotnet@v3
       with:
          dotnet-version: ${{ inputs.dotnet-version }}
     
     - name: Install dependencies
       run: dotnet restore
     
     - name: Build
       run: dotnet build ${{ inputs.projectPath }} --configuration Release -o release
     
     - uses: actions/upload-artifact@v3
       with:
         name: build-artifact
         path: release/