name: dotnet package

on: [push]

jobs:

  build-project:
    uses: mitzen/dotnet-gaction/.github/workflows/build.yaml@main
    with:
      projectPath: jeremywoo

  build-image:
    uses: mitzen/dotnet-gaction/.github/workflows/buildimage.yaml@main
    needs: build-project

    with:
      artifact: build-artifact
      repository: kepung
      tags: "dotnetaction"  