name: dotnet package

on: [push]

jobs:

  build-project:
    uses: mitzen/dotnet-gaction/.github/workflows/build.yaml@main
    with:
      projectPath: dotnet-gaction.csproj

  build-image:
    uses: mitzen/dotnet-gaction/.github/workflows/buildimage.yaml@main
    needs: build-project

    with:
      artifact: build-artifact
      repository: kepung
      tags: "dotnetaction"
    secrets:
      docker_username: ${{ secrets.DOCKERUSER}} 
      docker_token: ${{ secrets.DOCKERUSER}}

  kubernetes-deploy:
     uses: mitzen/dotnet-gaction/.github/workflows/kubernetes-deploy.yaml@main
     needs: [build-image]
     
     with: 
        resource_group: "myrg"
        imageName: "imagename"
        cluster_name: "clustername"
        environment: "production"
        container_registry: "container_registry"
        chart_path: "chart_path"
     secrets:
        AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
     