on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string
  
jobs:

 test:
   runs-on: ubuntu-latest
   steps:
     - name: Login Fake 
       run: |
           echo "paramter value passed from above"
           echo ${{ inputs.name }}
           echo "SECRET" 
     - name: Test 
       run: | 
           echo "testing done it all up and down"
           echo ${{ inputs.name }}