on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string
  
jobs:

 test:
   runs-on: ubuntu-latest
   steps:
     - name: Login Fake 
       run: |
           echo "variable"
           echo $MYVAR
           echo "SECRET" 
